Add 卒業試験課題2
munehiro1999/mokumoku pull request #1
Opened 2023-01-15 09:20 UTC by munehiro1999

こちらRSpecのスクリーンショット結果です。
レビューお願いします。

[![Image from Gyazo](https://i.gyazo.com/cc73da0fda7f3f68d390ed01a2dadefb.png)](https://gyazo.com/cc73da0fda7f3f68d390ed01a2dadefb)

2023-01-16 00:07 UTC, busitora requested changes
コメントしました！

2023-01-16 00:07 UTC, busitora commented on app/models/relationship.rb
> +  belongs_to :followeb, class_name: "User"
フォローしている人 なら 下記の方が一般的かと！
```suggestion
  belongs_to :following, class_name: "User"
```

2023-01-16 00:07 UTC, busitora commented on app/views/relationships/followers.html.erb
> +<h1>Relationships#followers</h1>
不要なファイルは削除してください！

2023-01-16 00:07 UTC, busitora commented on app/views/relationships/followings.html.erb
> +<h1>Relationships#followings</h1>
不要なファイルは削除してください！

2023-01-16 00:07 UTC, busitora commented on spec/factories/relationships.rb
> +    follower_id { 1 }
マジックナンバーの記載は辞めましょう！

2023-01-16 00:07 UTC, busitora commented on spec/models/relationship_spec.rb
> +require 'rails_helper'
不要なファイルは削除してください！もしくはmodel spec を作成してください

2023-01-16 00:07 UTC, busitora commented on spec/views/relationships/followers.html.erb_spec.rb
> +require 'rails_helper'
不要なファイルは削除してください！

2023-01-16 00:07 UTC, busitora commented on spec/views/relationships/followings.html.erb_spec.rb
> +require 'rails_helper'
不要なファイルは削除してください！

2023-01-16 11:19 UTC, munehiro1999 commented
課題修正しました
再度レビューお願いします。

2023-01-16 11:28 UTC, busitora requested changes

2023-01-16 11:28 UTC, busitora commented on spec/factories/relationships.rb
> +    follower_id { 1 }
マジックナンバー は調べましたか?

id の数値を書くのではなく、アソシエーションで紐付けてくださいm(_ _)m

2023-01-16 11:28 UTC, busitora commented on app/models/relationship.rb
> +  belongs_to :followeb, class_name: "User"
following に変更したことによる副作用は確認済みでしょうか?
テスト結果のスクリーンショットもあわせて添付お願いします。

2023-01-16 20:08 UTC, munehiro1999 commented
レビューお願いいたします。
spec/factores/relationships.rbは、数値の記載をやめ
修正した内容でよろしかったでしょうか？

rspecの結果です。
[![Image from Gyazo](https://i.gyazo.com/22b87e0918a5e74be2c8dfc1372430bb.png)](https://gyazo.com/22b87e0918a5e74be2c8dfc1372430bb)

2023-01-17 01:14 UTC, Tsuchiya2 commented
今後はレビューいただいたコメント1つに対して1コミットするようにしましょう。
その上で各コメントにどのコミットで変更したかを投稿するようにすると親切です。（[2689f98](https://github.com/munehiro1999/mokumoku/pull/1/commits/2689f982292dd08a2ef26e24299f9e8c958f6ca9) 本プルリクエスト上にあるリンクをコピーすると左記のようなリンクが生成されます。）

2023-01-17 01:17 UTC, Tsuchiya2 reviewed
コメントしました。
ご確認をお願いします。

2023-01-17 01:17 UTC, Tsuchiya2 commented on app/decorators/relationship_decorator.rb
> +class RelationshipDecorator < Draper::Decorator
こちらのファイル、使用していないようだったら削除しましょう。（他のファイルも同様です）

2023-01-17 01:17 UTC, Tsuchiya2 commented on app/views/relationships/followings.html.erb
> +<h1>Relationships#followings</h1>
こちらのファイルも削除できていないようなので確認をお願いします。

2023-01-17 01:17 UTC, Tsuchiya2 commented on config/routes.rb
> +  get 'relationships/followebs'
重複しているものがあるので確認をお願いします。（他の箇所を確認して不要なら削除しましょう）

2023-01-17 07:32 UTC, munehiro1999 commented
[2689f98](https://github.com/munehiro1999/mokumoku/pull/1/commits/2689f982292dd08a2ef26e24299f9e8c958f6ca9)

2023-01-17 07:37 UTC, munehiro1999 commented on config/routes.rb
> +  get 'relationships/followebs'
重複を修正しました
[8a2ed01](https://github.com/munehiro1999/mokumoku/pull/1/commits/8a2ed011fe209df9df76ac7a5dc7cb0dc82d22f1)

2023-01-17 07:37 UTC, munehiro1999 commented on app/decorators/relationship_decorator.rb
> +class RelationshipDecorator < Draper::Decorator
ファイルを削除しました
[8a2ed01](https://github.com/munehiro1999/mokumoku/pull/1/commits/8a2ed011fe209df9df76ac7a5dc7cb0dc82d22f1)

2023-01-17 07:47 UTC, munehiro1999 commented
>今後はレビューいただいたコメント1つに対して1コミットするようにしましょう。
その上で各コメントにどのコミットで変更したかを投稿するようにすると親切です。（[2689f98](https://github.com/munehiro1999/mokumoku/pull/1/commits/2689f982292dd08a2ef26e24299f9e8c958f6ca9) 本プルリクエスト上にあるリンクをコピーすると左記のようなリンクが生成されます。）

承知しました！今後レビューいただいたコメントに対して分かりやすいようにコミットすることを気をつけます！

2023-01-17 11:23 UTC, enda1111 reviewed
コメントしました。
ご確認をお願いします。

2023-01-17 11:23 UTC, enda1111 commented on app/models/relationship.rb
> +  belongs_to :followeb, class_name: "User"
followingとfollowerの組み合わせが一般的かなと思います。

2023-01-17 11:23 UTC, enda1111 commented on app/decorators/relationship_decorator.rb
> +class RelationshipDecorator < Draper::Decorator
こちらのファイル削除できていないですね。

2023-01-17 17:04 UTC, munehiro1999 commented
>followingとfollowerの組み合わせが一般的かなと思います。
>こちらのファイル削除できていないですね。

再度修正しました。よろしくお願いします。
[34b1d13](https://github.com/munehiro1999/mokumoku/pull/1/commits/34b1d13fa2ebad577e5fd8449e7755ede90b85ed)

2023-01-19 10:19 UTC, busitora approved these changes
LGTM!

(コメント残ってしまっていますが先日のが反映されていないようでした)

2023-01-19 10:34 UTC, merged